service: serverless_zendesk 

plugins:
  # - serverless-dynamodb-local
  - serverless-offline
# custom:
#   dynamodb:
#     start:
#       port: 8000
#       inMemory: true
#       migrate: true
#     migration:
#       dir: offline/migrations


provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http: 
          path: /
          method: get
          cors: true

  show:
    handler: show.show
    events:
      - http: 
          path: /show
          method: get
          cors: true

  list:
    handler: list/list.list
    events:
      - http: 
          path: /list
          method: get
          cors: true        

  create:
    handler: create/create.create
    events:
      - http: 
          path: /create
          method: post
          cors: true 

  update:
    handler: update/update.update
    events:
      - http: 
          path: /update/{id}
          method: put
          cors: true 

  delete:
    handler: delete/delete.delete
    events:
      - http: 
          path: /delete/{id}
          method: delete
          cors: true 
